### PR TITLE
Updated broken links

### PR DESCRIPTION
**Pull request by LotharukpongJS**
All the broken links are fixed (afaiaa).

- MBE has zipped all the supplementary files so an additional `utils::unzip()` line is now needed to obtain the `*xls` or *.xlsx` files.
- For BMC and Nature links, the addresses for the supplementary files were just changed so nothing much had to be done.
- I changed the Phylostratum column from the GenEra paper from `character` to `dbl` using `dplyr::mutate()`. This issue was overlooked in the previous pull request.

### CODE REVIEW

**Comment by HajkD** [comment]
Dear @LotharukpongJS 

Excellent work! Thank you very much.

Now everything should be in order, correct?

With very best wishes,
Hajk

**Comment by LotharukpongJS** [comment]
Dear @HajkD

Yes, it should be! Over time, we should start adding phylomaps published between 2016 and 2022 - and organise them for easy download perhaps as an R data package.

Best,
Sodai

**Comment by HajkD** [comment]
Fantastic idea! Feel free to open a GitHub issue with a `feature` request label. Maybe some other phylomap users can help us find all such studies we can list.

**Comment by HajkD** [comment]
Dear @LotharukpongJS 

I was also thinking that a Table of Content would be great, since it would allow users to quick jump to their favourite species of itnerest.

The ToC structure could be as follows:

- `Drosophila melanogaster` (fly)
    - PhyloMap Year (2010)
    - PhyloMap Year (2015)
- `Arabidopsis thaliana` (thale cress)
    - PhyloMap Year (2012)
    - PhyloMap Year (2015)

etc.

The individual pullet points can then link to the respective study.

What do you think?

Cheers,
Hajk

**Pull request merged**
